### ISSUE TITLE
Exit viewport only called when element passes out the bottom of the viewport?

### ISSUE THREAD

**Issue by alexr8** [russellgoldenberg/enter-view#14]
Hi, this is a great library. I'm not sure if this is expected behaviour, but if i have an element that scrolls into view, the enter event is fired as expected. If i keep scrolling so that the element disappears out the top of the viewport, the exit event is not fired, its only fired when i scroll back up past the element and it disappears out the bottom of the viewport. Is this as intended? Is there a way to make it detect whether it has exited either the top and bottom of the viewport so I can tell if it is currently in view right now or not?

**Comment by russellsamora** [comment]
this is the intended effect, basically direction is included by default. if entering is defined as when it scrolls into view (as the user scrolls down), exiting is when it reverses and scrolls out of view (as the user scrolls up).

**Comment by alexandergantikow** [comment]
I had hoped that the library would provide the functionality described by alexr8 above. In my application, I use a D3 graph in which I highlight the nodes that a user currently sees in the viewport. Because the events only ever fire in one direction, my graph nodes remain highlighted.
